pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'gallery-frontend'
        DOCKER_TAG = 'latest'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('frontend') {
                    script {
                        docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}")
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                sh "docker-compose up -d frontend"
            }
        }
    }
}
